<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-27 13:57
=======
# Generated by Django 5.2.1 on 2025-05-08 12:19
>>>>>>> main

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_content', '0002_remove_contenu_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to=settings.AUTH_USER_MODEL),
        ),
    ]
