# Generated by Django 5.2.1 on 2025-05-27 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'author', 'body')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('title', 'body')},
        ),
    ]
