# Generated by Django 5.2 on 2025-04-12 13:12

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=patient.models.generate_patient_id, editable=False, max_length=10, unique=True),
        ),
    ]
