# Generated by Django 5.2 on 2025-04-12 10:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_maladie',
            field=models.DateField(default=datetime.date(2025, 4, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='type_diabete',
            field=models.CharField(default=datetime.date(2025, 4, 12), max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActiviteSportive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('type_activite', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='InjectionInsuline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('dose', models.FloatField()),
                ('type_insuline', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MesureGlycemie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('contexte', models.CharField(max_length=100)),
                ('valeur', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glycemies', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Proche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('type_relation', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proches', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_repas', models.DateTimeField()),
                ('type_repas', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TensionArterielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('diastolique', models.IntegerField()),
                ('systolique', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tensions', to='patient.patient')),
            ],
        ),
    ]
