# Generated by Django 5.2 on 2025-04-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_weightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField(help_text='Insulin dose in units (UI)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional note (e.g., before meal, after exercise)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulin_records', to='patient.patient')),
            ],
        ),
    ]
