# Generated by Django 5.2 on 2025-05-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0006_insulinrecord"),
    ]

    operations = []
