# Generated by Django 5.2 on 2025-05-24 10:04

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0007_fix_type_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitesportive',
            old_name='type_activite',
            new_name='type_activity',
        ),
    ]