# Generated by Django 5.2 on 2025-05-24 10:11

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0008_rename_type_activite_to_activity"),
    ]

    operations = [migrations.AddField(
          model_name='activitesportive',
           name='duration',
           field=models.PositiveIntegerField(help_text='Duration in minutes')     )]
