# Generated by Django 5.2.1 on 2025-05-27 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_rename_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitesportive',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitesportive',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='activitesportive',
            name='type_activity',
            field=models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('strength_training', 'Strength Training'), ('other', 'Other')], max_length=100),
        ),
    ]
