# Generated by Django 5.2.1 on 2025-05-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INPE', models.CharField(blank=True, max_length=20)),
                ('horaire_travail', models.CharField(blank=True, max_length=100)),
                ('consultationPrice', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('jours_disponible', models.CharField(blank=True, max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('langues', models.ManyToManyField(related_name='medecins', to='medecin.langage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
