# Generated by Django 5.2 on 2025-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='medecin',
            name='INPE',
            field=models.CharField(default='default_inpe', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medecin',
            name='city',
            field=models.CharField(default='rabat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medecin',
            name='consultationPrice',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='medecin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='horaire_travail',
            field=models.CharField(default='monday to friday', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medecin',
            name='jours_disponible',
            field=models.CharField(default='lundi mardi mercredi jeudi vendredi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medecin',
            name='address',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='medecin',
            name='langues',
            field=models.ManyToManyField(related_name='medecins', to='medecin.langage'),
        ),
    ]
