# Generated by Django 5.2 on 2025-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_langage_remove_medecin_phone_number_medecin_inpe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='horaire_travail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='jours_disponible',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
