# Generated by Django 5.2 on 2025-04-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_alter_medecin_horaire_travail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='INPE',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
